### PR TITLE
adding py.typed to enable mypy, if used as library

### PR DESCRIPTION
**Pull request by daringer**
This package is well typed, in order to use it as a library it should be marked as typed as explained here: https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

This PR adds a `py.typed` file and includes it inside `pyproject.toml` so anyone including this package as a library/dependency can use `mypy` for type-checking.

### CODE REVIEW

**Comment by dainnilsson** [comment]
Thanks! Though looking at the provided link, shouldn't the py.typed file be located in the `fido2` directory rather than the root?

**Comment by daringer** [comment]
yes, you are right, the final `py.typed` file did not end up where it should. Made the necessary changes and tested like that (with the repository being the current work directory):
```
# set up virtual env
$ python -m venv /tmp/my-test-venv
# install python-fido2 into virtual env
$ /tmp/my-test-venv/bin/python -m pip install .
# check if py.typed is at the right spot
$ stat /tmp/my-test-venv/lib/python-3.*/site-packages/fido2/py.typed
```

**Comment by dainnilsson** [comment]
You shouldn't need the change to pyproject.toml, the file should get included anyway.

**Comment by daringer** [comment]
Indeed, updated!

**Comment by dainnilsson** [comment]
Thanks! Merged!

**Pull request merged**
