### PR TITLE
Added support of iso14443-4 extended apdu.

### PR DESCRIPTION
**Pull request by merlokk**

### CODE REVIEW

**Comment by merlokk** [comment]
travis happy. all is ok)

**Comment by dainnilsson** [comment]
Thanks. Are you aware of any authenticators that only work with extended APDUs? If there are then this seems like a reasonable addition. If not, then I may need more convincing as to why this is needed.

**Comment by merlokk** [comment]
by now i dont know. but they may appear sometime)
the main reason - sometimes needs to have pure extended apdu channel for some application or for device's tests

**Comment by merlokk** [comment]
btw) some readers have bugs in some channels...  now i work with HID reader that have bugs in extended channel and may be somewhere reader with bug in 7816 chaining. so it will be great to have several channels

**Comment by dainnilsson** [comment]
Ok, seems reasonable. One small thing though, can you rename the field to `use_ext_apdu` instead of `work_via_ext_apdu`?

**Comment by merlokk** [comment]
sure

**Comment by merlokk** [comment]
needs to squish? or its ok?

**Comment by dainnilsson** [comment]
Looks fine, merged. Thanks!

**Comment by merlokk** [comment]
Thank you!

**Pull request merged**
